### ISSUE TITLE
Class `.nav` op een `<nav>` element?

### ISSUE THREAD

**Issue by slimluccii** [Jason2426/the-client-website#7]
Is een beetje dubbel op. Misschien wil je gewoon in de css naar het nav element linken. Of een meer betekenisvollere class geven, zoals `.main-nav` of `.menu`

https://github.com/Jason2426/the-client-website/blob/e13ceb2617e573be6d8399ddc054d04c1fdf05a7/index.html#L12

**Comment by Jason2426** [comment]
Thx, ook gefixed voor de rest van de elementen 
https://github.com/Jason2426/the-client-website/blob/d12751a82a289456264d11ce697373dd1fe1bba5/index.html#L12C1-L17C11
